name: Sync to Hugging Face Spaces
on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push to Hugging Face spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install -U huggingface_hub
          huggingface-cli login --token $HF_TOKEN
          huggingface-cli space upload ashshettyyy/neural-style-transfer


      

      
