name: Sync to Hugging Face hub with LFS
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Push to Hugging Face with LFS
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Set up Git LFS for Hugging Face
          git lfs install
          git lfs track "*.jpg"
          git lfs track "*.png"
          git lfs track "*.jpeg"
          git add .gitattributes
          git commit -m "Configure Git LFS for binary files" || true

          # Push to Hugging Face Space
          git push https://ashshettyyy:$HF_TOKEN@huggingface.co/spaces/ashshettyyy/neural-style-transfer main --force
